### ISSUE TITLE
Thunar integration by GUI

### ISSUE THREAD

**Issue by btesteracc** [novoid/appendfilename#2]
Hello Karl,
I learned about your tools by watching your presentation at the Frazer Linuxtage and tried them out afterwards. 
I think your tools are absolutely great and I can use them to improve my workflow. I'm using Thunar as a file manager and I integrated your tools through the GUI Edit / Custom Actions, so that I have them in the right click menu. There was no problem with that at all and I think it is easier than editing the config of Thunar the way you are mentioning it in the readme.  The only thing that is a little bit strange on my desktop is the position of the window that is opening in interactive mode. But this is an issue that comes because of my windows manager (i3) and is not related to thunar or your tools.

HAGO
Bjoern

**Comment by novoid** [comment]
Hi btesteracc,

Glad that my tools are able to help your workflows.

Thunar integration, well. The story is a bit complicated, I'm afraid. You're absolutely right: to get something to the Thunar context menu, Thunar GUI settings dialogue is sufficient. I found out that when I want to control the window properties of that opening shell, I had to write those wrapper shell scripts I added to the README. Mostly because of the `--geometry=` option.

And then, when you have those shell scripts, you can create those desktop files. This has the advantage that all decent file managers are offering `appendfilename` and the other tools for the file patterns given.

However, I'm not stating that there is no simpler solution. For Windows, I recently created https://github.com/novoid/integratethis which eases the Windows Explorer integration to big extend.

My plans for the future of `integratethis` is that I add Thunar and geeqie integration as well. It's not on my high prio list but it would result in a very cool user experience ;-)

If you'd like to send a pull request, I'd be delighted.

I'm going to close this issue for now (because from my point of view there is no issue to solve for now) but please do feel free to add comments here if you do have further ideas.
