### ISSUE TITLE
Help command line switch

### ISSUE THREAD

**Issue by metbril** [novoid/appendfilename#4]
I had to take a look at the code in this repo to find the available command line switches.
It would be nice if a `--help` and/org `-h` switch would show the syntax. Or, the syntax could be shown if no arguments are passed at all (instead of the current error message).

**Comment by novoid** [comment]
Hi @metbril,

I can not follow your issue since both, `-h` and `--help`, are implemented as described. If I did not understand your issue correctly, please do re-open this issue.

However, you've got a point: I should probably catch the situation when not a single command line argument is given and show the help information. I fixed this with https://github.com/novoid/appendfilename/commit/385ba28608855b3eb52643293f0d43ae0a24aba7.
