### ISSUE TITLE
Tried you geeqie setup in ubuntu 18.04, but terminal window appears and disappears immediately again

### ISSUE THREAD

**Issue by michaelsjackson** [novoid/appendfilename#7]
Not sure why.  Maybe you have some useful hints?
Thanks for sharing. Cool youtube video.

**Comment by novoid** [comment]
Thanks for the compliment. Minor correction: no YouTube involved. ;-)

It looks to me that you are able to invoke the terminal window, then something writes an error(?) message to the screen and terminates the window afterwards.

In order to read the standard out or error message, you can add a line with "read" at the end of the shell script which is called by geeqie. This way, you have to press "Enter" to close the terminal window. Try this and you'll get a hint what's going wrong.

Please report back so that we're able to close this issue after your setup is working.

**Comment by michaelsjackson** [comment]
Dear Karl, thanks for the quick response.

I tried now from command line, it seems it did not like -x option, tried then -e, did not like that, too.
Tried
```
--
command.sh
```
this seems to work, but now:
`__init__.py: error: no such option: --interactive`

I just got it from your github today. Any more hints?

Here is my geeqie called shell script:
```

#!/usr/bin/env bash

/usr/bin/gnome-terminal \
--geometry=73x5+330+5  \
--hide-menubar \
-- 
/home/mj/geeqie/appendfilename/appendfilename/__init__.py --interactive "${@}"

#end

```

**Comment by novoid** [comment]
My fault as it seems: the `--interactive` was a command line parameter to indicate the interactive mode, where the tool asks from the user in an interactive way in contrast to expect everything via parameters.

I later found out that this option is not necessary: when the user did not provide all necessary parameters, the tool asks for them interactively. I just forgot to remove the deprecated option from the examples. Sorry for that. I fixed it. Please remove the `--interactive` and you should be fine.

**Comment by michaelsjackson** [comment]
I found it out later while testing directly from command line, thanks for adding back here.
